server:
  #?????
  port: 7082
spring:
  application:
    #????????????
    name: cloud-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7080/eureka
  #????????????
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:7082
