spring:
  application:
    name: cloud-provider
server:
  port: 7081

eureka:
  client:
    #????????eureka????????????????true
    fetch-registry: false
    #?????eureka???????????????????????true,????????
    register-with-eureka: true
    service-url:
      #defaultZone ????????????????
      #????????service-url,??????map?key-value?????key?defaultZone??????????????????
      #??????????defaultZone?
      defaultZone: http://localhost:7080/eureka
  #????????????
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:7081
